/**
 * tasksStyles.ts — ZenTrack Tasks Module
 *
 * All StyleSheet.create() calls for the Tasks screen and its sub-components.
 * Extracted to prevent 830 lines of style code from being parsed in the
 * main TasksScreen coordinator file.
 */
import { StyleSheet } from 'react-native';
import { FONT_FAMILY, FONT_SIZE, SPACE, RADIUS, SHADOW } from '../../theme/tokens';

export const makeTasksStyles = (colors: any, isDark: boolean = true) => StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  captureBar: {
    backgroundColor: isDark ? (colors.surface2 || colors.surface) : colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 20,
  },
  captureText: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 13.5, color: colors.textTertiary, marginHorizontal: 12 },

  // Date Selector
  jumpBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: isDark ? (colors.surface2 || colors.surface) : colors.surface,
    borderRadius: 8,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: colors.border,
  },
  jumpBtnText: { fontSize: 12, color: colors.textSecondary, fontWeight: '500' },
  dateSelectorContainer: { paddingHorizontal: 0, paddingTop: 0 },
  dateRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  dateItem: {
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 12,
    width: 44,
    backgroundColor: isDark ? 'transparent' : colors.surface,
    borderWidth: isDark ? 0 : 1,
    borderColor: isDark ? 'transparent' : colors.border,
  },
  dateItemActive: { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary },
  viewToggle: {
    flexDirection: 'row',
    backgroundColor: isDark ? (colors.surface2 || colors.surface) : '#EAE9F2',
    borderRadius: RADIUS.full,
    padding: 2,
  },
  viewToggleBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: RADIUS.full },
  viewToggleBtnActive: { backgroundColor: isDark ? (colors.surfaceRaised || colors.border) : '#FFFFFF' },
  addBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' },
  listSectionTitle: { fontSize: 12, fontWeight: '600', color: colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  listSectionHeader: { paddingHorizontal: 20, paddingVertical: 6, marginTop: 12 },
  progressTrack: { height: 4, backgroundColor: isDark ? colors.border : '#E2E1EA', marginTop: 10, borderRadius: 2 },
  progressBar: { height: 4, backgroundColor: colors.accentPrimary, borderRadius: 2 },
  dateItemToday: { borderWidth: 0, backgroundColor: 'transparent' },
  dateMonthActive: { color: '#ffffff', fontWeight: '600' },
  dateMonth: { fontSize: 10, fontWeight: '400', color: colors.textTertiary, marginBottom: 2 },
  dateNum: { fontSize: 14, fontWeight: '400', color: colors.textPrimary },
  dateNumActive: { color: isDark ? '#000000' : '#ffffff', fontWeight: '700' },
  dateDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.accentPrimary, marginLeft: 4 },
  dateDay: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: colors.textMuted, marginTop: 4 },

  // Section Header
  sectionHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', paddingHorizontal: SPACE.xl, paddingTop: SPACE.xl, paddingBottom: SPACE.sm },
  emptyTitle: { fontFamily: FONT_FAMILY.title, fontSize: FONT_SIZE.lg, color: colors.textPrimary, marginTop: SPACE.lg },
  emptySub: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: colors.textMuted, marginTop: SPACE.xs, textAlign: 'center' },
  subtaskPrepopulated: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4, marginBottom: 8 },
  subtaskPrepopulatedText: { fontFamily: FONT_FAMILY.body, fontSize: 11, color: colors.textSecondary, textDecorationLine: 'line-through' },
  xpPopup: { position: 'absolute', right: 20, top: -10, backgroundColor: colors.accentGreen, paddingHorizontal: 12, paddingVertical: 4, borderRadius: RADIUS.full, ...SHADOW.md },
  xpPopupText: { fontFamily: FONT_FAMILY.bold, fontSize: 12, color: isDark ? '#000000' : '#ffffff' },
  sectionTitle: { fontSize: 26, fontWeight: '700', color: colors.textPrimary, marginBottom: 4 },
  sectionSub: { fontSize: 12, fontWeight: '400', color: colors.textTertiary },
  sectionDivider: { height: 1, backgroundColor: colors.border, marginTop: 18, marginBottom: 24 },
  bulkEditBtn: { flexDirection: 'row', alignItems: 'center', gap: SPACE.xs, paddingHorizontal: SPACE.md, paddingVertical: 8, borderRadius: RADIUS.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  bulkActionBar: { position: 'absolute', bottom: 90, left: 16, right: 16, backgroundColor: colors.surface, borderRadius: RADIUS.lg, flexDirection: 'row', alignItems: 'center', paddingVertical: SPACE.md, ...SHADOW.lg, borderWidth: 1, borderColor: colors.border, zIndex: 100 },
  bulkActionBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  bulkActionCircle: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5 },
  bulkActionText: { fontFamily: FONT_FAMILY.medium, fontSize: FONT_SIZE.md, color: colors.accentPrimary },
  bulkActionDivider: { width: 1, height: 30, backgroundColor: colors.border },
  bulkEditText: { fontFamily: FONT_FAMILY.bold, fontSize: FONT_SIZE.sm, color: colors.textPrimary },
  list: { paddingHorizontal: 0, paddingTop: SPACE.xl, paddingBottom: 120, gap: 0 },

  // New Task Form
  newTaskCard: { backgroundColor: colors.accentDim, borderRadius: RADIUS.xl, borderWidth: 1, borderColor: colors.border, padding: SPACE.lg, marginBottom: SPACE.xl, marginTop: SPACE.sm },
  newTaskHeader: { flexDirection: 'row', alignItems: 'center', gap: SPACE.sm, marginBottom: SPACE.md },
  newTaskIconBox: { width: 28, height: 28, borderRadius: 6, backgroundColor: colors.accentDim, alignItems: 'center', justifyContent: 'center' },
  newTaskTitle: { fontFamily: FONT_FAMILY.bold, fontSize: FONT_SIZE.sm, color: colors.textPrimary, letterSpacing: 1 },
  newTaskInputRow: { flexDirection: 'row', alignItems: 'center', gap: SPACE.sm, marginBottom: SPACE.md },
  newTaskInput: { flex: 1, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.md, padding: SPACE.md, fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.md, color: colors.textPrimary },
  optionsBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.md, paddingHorizontal: SPACE.md, paddingVertical: 14 },
  optionsBtnText: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: colors.textMuted },
  addTaskBtn: { backgroundColor: colors.accentDim, borderWidth: 1, borderColor: colors.accentPrimary, borderRadius: RADIUS.lg, alignItems: 'center', justifyContent: 'center', paddingVertical: 12, alignSelf: 'flex-start', paddingHorizontal: SPACE.xl },
  addTaskBtnText: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.sm, color: colors.accentPrimary },

  // Options Panel
  optionsPanel: { backgroundColor: isDark ? (colors.surface2 || colors.surface) : colors.surface2, borderRadius: RADIUS.lg, padding: SPACE.md, marginTop: SPACE.md, gap: SPACE.md },
  optRow: { flexDirection: 'row', gap: SPACE.sm, flexWrap: 'wrap', alignItems: 'center' },
  priorityPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6, borderRadius: RADIUS.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  priorityDot: { width: 8, height: 8, borderRadius: 4 },
  priorityPillText: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: colors.textMuted },
  timeBox: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: RADIUS.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  timeInput: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: colors.textPrimary, minWidth: 40, textAlign: 'center' },
  estTimeBox: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: RADIUS.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  estInput: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: colors.textPrimary, minWidth: 40 },
  recurPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6, borderRadius: RADIUS.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  recurPillText: { fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.xs, color: colors.textMuted },
  card: { flexDirection: 'row', backgroundColor: colors.surface, borderBottomWidth: 1, borderColor: colors.border, overflow: 'hidden' },
  cardSelected: { borderColor: colors.accentPrimary, backgroundColor: isDark ? colors.accentDim : 'rgba(108,92,231,0.08)' },
  cardContent: { flex: 1, flexDirection: 'row', alignItems: 'center', padding: SPACE.md, gap: SPACE.sm },
  dragHandle: { width: 12, height: 18, flexDirection: 'row', flexWrap: 'wrap', gap: 2, justifyContent: 'center', alignItems: 'center', opacity: 0.3 },
  dragDot: { width: 3, height: 3, borderRadius: 1.5, backgroundColor: colors.textTertiary },
  customCheckbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 1.5, borderColor: isDark ? '#3A3A3C' : '#D1D1D6', backgroundColor: isDark ? 'transparent' : '#F4F3F8', alignItems: 'center', justifyContent: 'center' },
  customCheckboxDone: { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary },
  bulkCheckbox: { width: 22, height: 22, borderRadius: 11, borderWidth: 1.5, borderColor: isDark ? '#3A3A3C' : '#D1D1D6', alignItems: 'center', justifyContent: 'center' },
  bulkCheckboxSelected: { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary },
  taskMeta: { flex: 1, gap: 4 },
  taskTitle: { fontFamily: FONT_FAMILY.bold, fontSize: FONT_SIZE.md, color: colors.textPrimary },
  taskDone: { textDecorationLine: 'line-through', color: colors.textTertiary },
  taskFooter: { flexDirection: 'row', gap: SPACE.xs, flexWrap: 'wrap', alignItems: 'center' },
  pill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: SPACE.xs, paddingVertical: 2, borderRadius: RADIUS.full, borderWidth: 1, borderColor: colors.border, backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.04)' },
  pillText: { fontFamily: FONT_FAMILY.body, fontSize: 11 },
  cardActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  actionBtnIcon: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface2 },
  empty: { alignItems: 'center', paddingVertical: 40, gap: SPACE.md },
  emptyText: { fontFamily: FONT_FAMILY.body, fontSize: 13, color: colors.textMuted, textAlign: 'center' },

  // Modal
  modalOverlay: { flex: 1, backgroundColor: isDark ? 'rgba(0,0,0,0.60)' : 'rgba(0,0,0,0.40)', justifyContent: 'center', padding: SPACE.xl },
  modalOverlayBottom: { flex: 1, backgroundColor: isDark ? 'rgba(0,0,0,0.60)' : 'rgba(0,0,0,0.40)', justifyContent: 'flex-end' },
  bottomSheetCard: { backgroundColor: colors.surface, borderTopLeftRadius: RADIUS.xxl, borderTopRightRadius: RADIUS.xxl, padding: 24, paddingBottom: 48, borderWidth: 1, borderColor: colors.border, borderBottomWidth: 0, ...SHADOW.lg },
  modalCard: { backgroundColor: colors.surface, borderRadius: RADIUS.xxl, borderWidth: 1, borderColor: colors.border, padding: SPACE.xxl, gap: SPACE.md, ...SHADOW.accent() },
  modalTitle: { fontFamily: FONT_FAMILY.title, fontSize: FONT_SIZE.lg, color: colors.textPrimary, marginBottom: SPACE.sm },
  modalInput: { backgroundColor: isDark ? colors.surface : colors.surface2, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.md, padding: SPACE.md, fontFamily: FONT_FAMILY.body, fontSize: FONT_SIZE.md, color: colors.textPrimary },
  cancelBtn: { flex: 1, paddingVertical: SPACE.md, borderRadius: RADIUS.md, borderWidth: 1, borderColor: colors.border, alignItems: 'center', backgroundColor: isDark ? 'transparent' : colors.surface2 },
  cancelBtnText: { fontFamily: FONT_FAMILY.bold, fontSize: FONT_SIZE.md, color: colors.textMuted },
  saveBtn: { flex: 2, paddingVertical: SPACE.md, borderRadius: RADIUS.md, backgroundColor: colors.accentPrimary, alignItems: 'center' },
  saveBtnText: { fontFamily: FONT_FAMILY.bold, fontSize: FONT_SIZE.md, color: isDark ? '#000000' : '#ffffff' },

  // Bulk Edit Bar
  rescheduleBtn: { backgroundColor: colors.accentPrimary, paddingHorizontal: SPACE.md, paddingVertical: SPACE.sm, borderRadius: RADIUS.md, flexDirection: 'row', alignItems: 'center', gap: SPACE.xs },
  rescheduleBtnText: { color: isDark ? '#000000' : '#ffffff', fontFamily: FONT_FAMILY.bold, fontSize: FONT_SIZE.sm },

  // New Task Modal
  newTaskInputLarge: { backgroundColor: 'transparent', borderWidth: 0, marginBottom: 0 },
  quickOptionsRow: { flexDirection: 'row', gap: 8, paddingVertical: 4 },
  quickChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: isDark ? '#0c0c0f' : '#F0EFF7',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: isDark ? '#1c1c22' : colors.border,
  },
  quickChipText: { fontSize: 13, fontWeight: '600', color: colors.textPrimary },
  addTaskBtnFull: {
    backgroundColor: colors.accentPrimary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  addTaskBtnDisabled: {
    backgroundColor: isDark ? '#141418' : colors.border,
  },
  addTaskBtnFullText: { fontSize: 15, fontWeight: '700', color: isDark ? '#000000' : '#ffffff' },
  addTaskBtnDisabledText: { color: colors.textMuted, fontWeight: '600' },

  // Subtasks panel
  subtasksPanel: { backgroundColor: isDark ? '#050507' : '#F8F7FC', borderWidth: 1, borderColor: isDark ? '#1c1c22' : colors.border, borderRadius: 12, padding: 10, marginBottom: 14, gap: 8 },
  subtaskRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  subtaskRowText: { flex: 1, fontSize: 13, fontWeight: '400', color: colors.textPrimary },
  subtaskInputRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 8 },
  subtaskInput: { flex: 1, fontSize: 13, color: colors.textPrimary, paddingVertical: 4 },
  subtaskAddBtn: { padding: 4 },

  // Edit modal priority pills
  editPriorityPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 20, borderWidth: 1.5, borderColor: colors.border, backgroundColor: colors.surface },
  editPriorityPillText: { fontSize: 12, fontWeight: '500', color: colors.textMuted },

  // Extracted styles
  autoStyle1: { flexGrow: 0 },
  autoStyle2: { padding: 4 },
  autoStyle116: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },

  // Top header
  topHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 8, paddingTop: 4, paddingBottom: 0, backgroundColor: colors.background },
  topHeaderTitle: { fontFamily: 'Inter_700Bold', fontSize: 28, color: colors.textPrimary },
  topHeaderIcons: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'flex-end', gap: 4 },
  iconBtn: { alignItems: 'center', width: 38 },
  badge: { position: 'absolute', top: -4, right: -4, backgroundColor: colors.accentPrimary, width: 16, height: 16, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  badgeText: { color: isDark ? '#000000' : '#ffffff', fontSize: 9, fontFamily: 'Inter_700Bold' },
  overdueBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: isDark ? 'rgba(255, 105, 97, 0.12)' : 'rgba(239, 68, 68, 0.08)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255, 105, 97, 0.25)' : '#FEE2E2',
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  overdueText: { color: colors.error, fontFamily: 'Inter_600SemiBold', fontSize: 13 },
  floatingAddContainer: { position: 'absolute', bottom: 110, left: 0, right: 0, alignItems: 'center' },
  menuOverlay: { flex: 1, backgroundColor: isDark ? 'rgba(0,0,0,0.50)' : 'rgba(0,0,0,0.25)', justifyContent: 'flex-start', alignItems: 'flex-end', paddingTop: 65, paddingRight: 20 },
  menuContainer: { backgroundColor: colors.surface, borderRadius: 12, width: 200, paddingVertical: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: isDark ? 0.2 : 0.08, shadowRadius: 12, elevation: 8, borderWidth: 1, borderColor: colors.border },
  menuItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 16 },
  menuItemText: { fontFamily: 'Inter_500Medium', fontSize: 16, color: colors.textPrimary },
  menuDivider: { height: 1, backgroundColor: colors.border, marginHorizontal: 16 },
  floatingAddBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.accentPrimary, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 24, shadowColor: colors.accentPrimary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.35, shadowRadius: 12, elevation: 4 },
  floatingAddText: { fontFamily: 'Inter_600SemiBold', fontSize: 14, color: isDark ? '#000000' : '#ffffff' },
  autoStyle113: { padding: 8 },
  listContent: { paddingBottom: 140 },
  autoStyle5: { flexGrow: 0, marginBottom: 12 },
  autoStyle6: { flexDirection: 'row', gap: 8, marginBottom: 16 },
  priorityDotSmall: { width: 6, height: 6, borderRadius: 3 },
  autoStyle8: { backgroundColor: colors.errorBg || '#fee2e2', padding: SPACE.md, borderRadius: RADIUS.md, marginBottom: SPACE.sm, borderWidth: 1, borderColor: colors.error || '#fca5a5' },
  autoStyle9: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
  autoStyle10: { fontFamily: FONT_FAMILY.bold, color: colors.error || '#b91c1c', fontSize: FONT_SIZE.sm },
  autoStyle11: { fontFamily: FONT_FAMILY.body, color: colors.error || '#991b1b', fontSize: FONT_SIZE.xs },
  autoStyle12: { paddingHorizontal: 24, marginTop: 12 },
  autoStyle13: { paddingHorizontal: 24 },
  tagsPanel: { paddingHorizontal: SPACE.md, paddingVertical: SPACE.sm, borderTopWidth: 1, borderTopColor: colors.border, gap: SPACE.sm },
  tagPillsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tagChip: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: SPACE.sm, paddingVertical: 4, borderRadius: 20, borderWidth: 1 },
  tagChipText: { fontFamily: 'Inter_500Medium', fontSize: 12 },
  tagSuggestion: { paddingHorizontal: SPACE.sm, paddingVertical: 4, backgroundColor: colors.surface, borderRadius: 20, borderWidth: 1, borderColor: colors.border },
  tagSuggestionText: { fontFamily: 'Inter_500Medium', fontSize: 12, color: colors.textPrimary },
  tagInputRow: { flexDirection: 'row', gap: SPACE.sm, alignItems: 'center' },
  tagInput: { flex: 1, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.md, paddingHorizontal: SPACE.md, paddingVertical: 8, fontFamily: 'Inter_400Regular', fontSize: FONT_SIZE.sm, color: colors.textPrimary },
  tagAddBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' },
});
