import { StyleSheet, Platform, StatusBar as RNStatusBar } from 'react-native';
import { FONT_FAMILY, SPACE, RADIUS, SHADOW } from '../../theme/tokens';

export const makeActiveLoggingStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: isDark ? '#000000' : colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACE.xl,
      paddingTop: Platform.OS === 'android' ? (RNStatusBar.currentHeight || 40) + 8 : 12,
      paddingBottom: SPACE.sm,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    backBtn: { padding: SPACE.xs },
    headerTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 13, color: colors.textMuted, letterSpacing: 1 },
    content: { flex: 1 },
    scrollContent: { padding: SPACE.xl, paddingBottom: 190 },

    titleArea: { marginBottom: SPACE.xl, alignItems: 'center' },
    musclePill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, marginBottom: 12 },
    muscleDot: { width: 6, height: 6, borderRadius: 3, marginRight: 6 },
    muscleText: { fontFamily: FONT_FAMILY.bold, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1 },
    exerciseName: { fontFamily: FONT_FAMILY.bold, fontSize: 20, color: colors.textPrimary, marginBottom: 4, textAlign: 'center', flexShrink: 1 },
    lastTimeText: { fontFamily: FONT_FAMILY.body, fontSize: 13, color: colors.textMuted, marginTop: 4 },
    overloadChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: RADIUS.md, marginTop: 12, gap: 6 },
    overloadChipText: { fontFamily: FONT_FAMILY.medium, fontSize: 12 },

    quickChipsContainer: {
      marginBottom: SPACE.md,
      marginHorizontal: -SPACE.xl,
      paddingHorizontal: SPACE.xl,
    },
    quickChipsScroll: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 2,
    },
    quickChipRepeat: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: 'rgba(165,153,255,0.14)',
      borderWidth: 1,
      borderColor: 'rgba(165,153,255,0.32)',
      paddingHorizontal: 11,
      paddingVertical: 6,
      borderRadius: RADIUS.full,
    },
    quickChipTextHighlight: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 11.5,
      color: '#a599ff',
    },
    quickChip: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface2,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.08)' : colors.border,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: RADIUS.full,
    },
    quickChipText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 11.5,
      color: colors.textPrimary,
    },
    quickChipDivider: {
      width: 1,
      height: 16,
      backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : colors.border,
      marginHorizontal: 2,
    },

    swipeTrack: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(52,199,89,0.15)',
      borderWidth: 1,
      borderColor: 'rgba(52,199,89,0.3)',
      borderRadius: RADIUS.md,
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: SPACE.md,
    },
    swipeTrackContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    swipeTrackText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 12,
      color: '#34C759',
    },

    setRowWrapper: {
      marginBottom: 8,
      borderRadius: RADIUS.md,
      overflow: 'hidden',
      position: 'relative',
    },
    setRowWrapperActive: {
      paddingLeft: 4,
    },
    activeIndicator: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: 4,
      backgroundColor: colors.accentPrimary,
    },
    setRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      paddingHorizontal: SPACE.md,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
      shadowColor: isDark ? '#000000' : 'rgba(0,0,0,0.03)',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 1,
    },
    setRowActive: {
      backgroundColor: isDark ? '#2C2C2E' : '#F0EFF7',
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 0,
      borderColor: colors.accentPrimary,
    },
    setRowCompleted: {
      backgroundColor: isDark ? 'transparent' : 'rgba(5, 150, 105, 0.04)',
      borderColor: isDark ? 'transparent' : colors.border,
    },
    setIndexArea: { width: 32, alignItems: 'center', justifyContent: 'center' },
    setIndexText: { fontFamily: FONT_FAMILY.bold, fontSize: 15, color: colors.textMuted },
    inputGroup: { flex: 1, marginHorizontal: 6, position: 'relative' },
    fakePlaceholder: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
    },
    fakePlaceholderText: {
      color: colors.textMuted,
      fontFamily: FONT_FAMILY.bold,
      fontSize: 16,
    },
    textInput: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : colors.surface2,
      borderRadius: RADIUS.sm,
      height: 44,
      paddingVertical: 0,
      fontFamily: FONT_FAMILY.bold,
      fontSize: 16,
      color: colors.textPrimary,
      textAlign: 'center',
      borderWidth: isDark ? 0 : 1,
      borderColor: colors.border,
    },

    addSetBtn: {
      alignSelf: 'center',
      paddingVertical: SPACE.md,
      paddingHorizontal: SPACE.xl,
      marginTop: SPACE.sm,
    },
    addSetBtnText: { fontFamily: FONT_FAMILY.bold, fontSize: 13, color: colors.accentPrimary },
    videoBtn: {
      padding: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    videoContainer: { borderRadius: RADIUS.md, overflow: 'hidden', marginBottom: SPACE.xl },

    mainBtnWrapper: { marginTop: SPACE.md, ...SHADOW.lg },
    mainBtn: {
      flexDirection: 'row',
      borderRadius: RADIUS.lg,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mainBtnComplete: { backgroundColor: isDark ? '#34C759' : colors.accentGreen },
    mainBtnIncomplete: { backgroundColor: isDark ? '#0c0c0f' : colors.surface, borderWidth: 1, borderColor: isDark ? '#1c1c20' : colors.border },
    mainBtnText: { fontFamily: FONT_FAMILY.bold, fontSize: 15, color: colors.textPrimary },

    modalOverlay: { flex: 1, backgroundColor: isDark ? 'rgba(0,0,0,0.6)' : 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
    modalContent: { backgroundColor: isDark ? '#000000' : (colors.surfaceRaised || colors.surface), borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, maxHeight: '80%', borderWidth: 1, borderColor: isDark ? '#1c1c20' : colors.border },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    modalTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 20, color: colors.textPrimary },
    modalSubtitle: { fontFamily: FONT_FAMILY.body, fontSize: 13, color: colors.textMuted, marginTop: 4 },
    altRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: isDark ? '#0c0c0f' : (colors.surface2 || '#F0EFF7'), padding: 16, borderRadius: 12, marginBottom: 12, borderWidth: 1, borderColor: isDark ? '#1c1c20' : colors.border },
    altText: { flex: 1, fontFamily: FONT_FAMILY.bold, fontSize: 16, color: colors.textPrimary, marginLeft: 12 },
  });
