import { StyleSheet, Platform } from 'react-native';
import { FONT_FAMILY, SPACE, RADIUS } from '../../theme/tokens';

export const makeExerciseSwapStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: isDark ? '#000000' : colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACE.lg,
      paddingTop: Platform.OS === 'ios' ? 10 : 20,
      paddingBottom: SPACE.sm,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    backBtn: { padding: SPACE.xs },
    headerTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 13, color: colors.textPrimary, letterSpacing: 1.5 },
    headerSub: { fontFamily: FONT_FAMILY.body, fontSize: 11, color: colors.textMuted, marginTop: 2 },

    originalCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      marginHorizontal: SPACE.lg,
      marginTop: SPACE.md,
      marginBottom: SPACE.sm,
      padding: SPACE.md,
      borderRadius: RADIUS.lg,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    originalCardLeft: { flex: 1, paddingRight: 8 },
    originalCardLabel: { fontFamily: FONT_FAMILY.bold, fontSize: 9, color: colors.textMuted, letterSpacing: 1.2, marginBottom: 2 },
    originalCardName: { fontFamily: FONT_FAMILY.bold, fontSize: 15, color: colors.textPrimary, textTransform: 'capitalize' },
    originalCardMeta: { fontFamily: FONT_FAMILY.body, fontSize: 11, color: colors.textMuted, marginTop: 2 },

    tabContainer: {
      flexDirection: 'row',
      marginHorizontal: SPACE.lg,
      marginVertical: SPACE.md,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: RADIUS.lg,
      padding: 3,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    tabBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 8,
      borderRadius: RADIUS.md,
    },
    tabBtnActive: {
      backgroundColor: colors.accentPrimary,
    },
    tabBtnText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 12,
      color: colors.textMuted,
    },
    tabBtnTextActive: {
      color: '#ffffff',
    },

    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      marginHorizontal: SPACE.lg,
      marginBottom: SPACE.sm,
      paddingHorizontal: SPACE.md,
      height: 42,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    searchIcon: { marginRight: SPACE.sm },
    searchInput: { flex: 1, fontFamily: FONT_FAMILY.body, fontSize: 14, color: colors.textPrimary, height: '100%' },

    chipRow: {
      paddingHorizontal: SPACE.lg,
      paddingBottom: SPACE.sm,
      gap: 8,
    },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: RADIUS.full,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    chipActive: {
      backgroundColor: colors.accentPrimary,
      borderColor: colors.accentPrimary,
    },
    chipText: {
      fontFamily: FONT_FAMILY.medium,
      fontSize: 11,
      color: colors.textMuted,
    },
    chipTextActive: {
      color: '#ffffff',
      fontFamily: FONT_FAMILY.bold,
    },

    list: { paddingHorizontal: SPACE.lg, paddingBottom: 120 },

    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: SPACE.sm,
      paddingHorizontal: 2,
    },
    sectionHeaderTitle: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 12,
      color: colors.accentPrimary,
      letterSpacing: 0.5,
    },
    sectionHeaderSub: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 10,
      color: colors.textMuted,
    },

    templateSwapCard: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: RADIUS.lg,
      padding: SPACE.md,
      marginBottom: SPACE.sm,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.18)' : 'rgba(108,92,231,0.2)',
    },
    templateSwapCardExact: {
      borderColor: colors.accentPrimary,
      backgroundColor: isDark ? '#1A1824' : '#F0EFF7',
    },
    templateCardTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    dayOriginPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: isDark ? 'rgba(165,153,255,0.12)' : 'rgba(108,92,231,0.1)',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: RADIUS.sm,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.2)' : 'rgba(108,92,231,0.2)',
    },
    dayOriginText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 10,
      color: colors.accentPrimary,
    },
    templateCardBody: {
      marginVertical: 4,
    },
    templateExName: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 16,
      color: colors.textPrimary,
      marginBottom: 2,
      textTransform: 'capitalize',
    },
    templateExMeta: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 12,
      color: colors.textMuted,
    },
    templateCardFooter: {
      marginTop: 6,
      paddingTop: 6,
      borderTopWidth: 1,
      borderTopColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    templateTapHint: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 11,
      color: colors.accentPrimary,
    },

    aiStatusBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? 'rgba(165,153,255,0.08)' : 'rgba(108,92,231,0.08)',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: RADIUS.md,
      marginBottom: SPACE.md,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.15)' : 'rgba(108,92,231,0.15)',
    },
    aiStatusTitle: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 12,
      color: colors.accentPrimary,
    },

    exerciseRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      padding: SPACE.md,
      borderRadius: RADIUS.md,
      marginBottom: SPACE.sm,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    exInfo: { flex: 1, paddingRight: SPACE.sm },
    exName: { fontFamily: FONT_FAMILY.bold, fontSize: 15, color: colors.textPrimary, marginBottom: 2, textTransform: 'capitalize' },
    exTarget: { fontFamily: FONT_FAMILY.body, fontSize: 12, color: colors.textMuted },
    exReason: { fontFamily: FONT_FAMILY.body, fontSize: 11, color: colors.accentPrimary, marginTop: 2 },

    templateBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      backgroundColor: isDark ? 'rgba(165,153,255,0.1)' : 'rgba(108,92,231,0.1)',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: RADIUS.sm,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.2)' : 'rgba(108,92,231,0.2)',
    },
    templateBadgeText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 9,
      color: colors.accentPrimary,
    },

    musclePill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
    muscleDot: { width: 6, height: 6, borderRadius: 3, marginRight: 4 },
    muscleText: { fontFamily: FONT_FAMILY.bold, fontSize: 10, textTransform: 'uppercase' },

    emptyState: { alignItems: 'center', marginTop: 60, gap: SPACE.md },
    emptyText: { fontFamily: FONT_FAMILY.body, fontSize: 14, color: colors.textMuted },
  });
