import { StyleSheet, Platform } from 'react-native';
import { FONT_FAMILY, SPACE, RADIUS, SHADOW } from '../../theme/tokens';

export const makeGymProgressStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: isDark ? '#000000' : colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      paddingTop: Platform.OS === 'ios' ? 8 : 16,
      paddingBottom: SPACE.md,
    },
    backBtn: { padding: 4 },
    headerTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 18, color: colors.textPrimary },
    filterTabs: { flexDirection: 'row', paddingHorizontal: SPACE.md, gap: 8, marginBottom: SPACE.md },
    tab: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 8,
      borderRadius: RADIUS.full,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    tabActive: {
      backgroundColor: isDark ? 'rgba(165,153,255,0.15)' : 'rgba(108,92,231,0.12)',
      borderColor: colors.accentPrimary,
    },
    tabText: { fontFamily: FONT_FAMILY.bold, fontSize: 12, color: colors.textMuted },
    tabTextActive: { color: colors.accentPrimary },
    content: { paddingHorizontal: SPACE.md, paddingBottom: 120 },
    kpiRow: { flexDirection: 'row', gap: SPACE.sm, marginBottom: SPACE.lg },
    kpiCard: {
      flex: 1,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: RADIUS.lg,
      padding: SPACE.sm,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
      ...SHADOW.sm,
    },
    kpiIconBox: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
    kpiValue: { fontFamily: FONT_FAMILY.bold, fontSize: 18, color: colors.textPrimary },
    kpiLabel: { fontFamily: FONT_FAMILY.medium, fontSize: 10, color: colors.textMuted, marginTop: 2 },
    glassCard: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: RADIUS.xl,
      padding: SPACE.lg,
      marginBottom: SPACE.lg,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
      ...SHADOW.sm,
    },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: SPACE.md },
    cardTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 16, color: colors.textPrimary },
    cardSubtitle: { fontFamily: FONT_FAMILY.medium, fontSize: 12, color: colors.textMuted, marginTop: 2 },
    cardHeaderBadge: { backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
    cardHeaderBadgeText: { fontFamily: FONT_FAMILY.bold, fontSize: 9, color: colors.textPrimary, letterSpacing: 0.5 },
    svgWrapper: { alignItems: 'center', marginTop: SPACE.xs },
    chartDateAxis: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginTop: 6, paddingHorizontal: 4 },
    axisDateText: { fontFamily: FONT_FAMILY.mono, fontSize: 10, color: colors.textMuted },
    donutContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: SPACE.md, gap: SPACE.md },
    donutSvgWrapper: { width: 150, height: 150, alignItems: 'center', justifyContent: 'center', position: 'relative' },
    donutCenterLabel: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
    donutCenterValue: { fontFamily: FONT_FAMILY.bold, fontSize: 18, color: colors.textPrimary },
    donutCenterSub: { fontFamily: FONT_FAMILY.medium, fontSize: 11, color: colors.textMuted },
    donutLegend: { flex: 1, gap: 8 },
    donutLegendRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    donutDot: { width: 10, height: 10, borderRadius: 5 },
    donutLegendName: { flex: 1, fontFamily: FONT_FAMILY.medium, fontSize: 13, color: colors.textPrimary },
    donutLegendPercent: { fontFamily: FONT_FAMILY.bold, fontSize: 13, color: colors.textMuted },
    cardioMetricsGrid: { flexDirection: 'row', gap: SPACE.sm, marginTop: SPACE.lg },
    cardioMetricBox: {
      flex: 1,
      backgroundColor: isDark ? '#2C2C2E' : colors.surface2,
      borderRadius: RADIUS.md,
      padding: SPACE.sm,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    cardioMetricValue: { fontFamily: FONT_FAMILY.bold, fontSize: 16, color: colors.textPrimary, marginTop: 8 },
    cardioMetricLabel: { fontFamily: FONT_FAMILY.medium, fontSize: 10, color: colors.textMuted, marginTop: 2 },
    chipScroll: { gap: 6, marginBottom: SPACE.md },
    chip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: RADIUS.full,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    chipActive: {
      borderColor: colors.accentPrimary,
      backgroundColor: isDark ? 'rgba(165,153,255,0.1)' : 'rgba(108,92,231,0.1)',
    },
    chipText: { fontFamily: FONT_FAMILY.medium, fontSize: 12, color: colors.textMuted },
    chipTextActive: { color: colors.accentPrimary },
    pillScroll: { gap: 8, paddingVertical: 4, marginBottom: SPACE.sm },
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: RADIUS.lg,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    pillActive: { backgroundColor: colors.accentGreen, borderColor: colors.accentGreen },
    pillText: { fontFamily: FONT_FAMILY.bold, fontSize: 13, color: colors.textMuted },
    pillTextActive: { color: '#ffffff' },
    emptyBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: SPACE.xl, gap: 8 },
    emptyText: { fontFamily: FONT_FAMILY.medium, fontSize: 12, color: colors.textMuted, textAlign: 'center' },
  });
