import { StyleSheet } from 'react-native';
import { FONT_FAMILY, SPACE, RADIUS } from '../../theme/tokens';

export const makeWorkoutSummaryStyles = (colors: any, isDark: boolean) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: isDark ? '#000000' : colors.background },
    header: { paddingHorizontal: SPACE.xl, paddingTop: 10, alignItems: 'flex-start' },
    backBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
      borderRadius: RADIUS.full,
    },
    content: { flexGrow: 1, paddingHorizontal: 8, paddingTop: SPACE.lg },
    heroSection: { alignItems: 'center', marginVertical: SPACE.lg },
    badgeHalo: { marginBottom: SPACE.md },
    haloGradient: { padding: 6, borderRadius: RADIUS.full, alignItems: 'center', justifyContent: 'center' },
    badgeWrapper: {
      width: 54,
      height: 54,
      borderRadius: RADIUS.full,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.3)' : colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sessionPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: isDark ? 'rgba(94, 218, 158, 0.08)' : 'rgba(5, 150, 105, 0.1)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(94, 218, 158, 0.2)' : 'rgba(5, 150, 105, 0.25)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: RADIUS.full,
      marginBottom: SPACE.md,
    },
    pulseDot: { width: 6, height: 6, borderRadius: RADIUS.full, backgroundColor: isDark ? '#5eda9e' : colors.accentGreen },
    sessionPillText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 10,
      color: isDark ? '#5eda9e' : colors.accentGreen,
      letterSpacing: 0.6,
    },
    heroTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 27, color: colors.textPrimary, textAlign: 'center', letterSpacing: -0.4, marginBottom: 4 },
    heroSubtitle: { fontFamily: FONT_FAMILY.body, fontSize: 14, color: colors.textMuted, textAlign: 'center' },
    prCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: 16,
      padding: 16,
      marginBottom: SPACE.lg,
      gap: SPACE.md,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    prIconBox: { width: 36, height: 36, borderRadius: RADIUS.md, backgroundColor: 'rgba(255, 107, 107, 0.15)', alignItems: 'center', justifyContent: 'center' },
    prTag: { fontFamily: FONT_FAMILY.bold, fontSize: 10, color: '#FF6B6B', letterSpacing: 0.6, marginBottom: 2 },
    prText: { fontFamily: FONT_FAMILY.bold, fontSize: 15, color: colors.textPrimary },
    statsGrid: { flexDirection: 'row', gap: 8, marginBottom: SPACE.xl },
    statBox: {
      flex: 1,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: 12,
      paddingVertical: 14,
      paddingHorizontal: 4,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    statNumber: { fontFamily: FONT_FAMILY.bold, fontSize: 18, color: colors.textPrimary, marginBottom: 3 },
    statLabel: { fontFamily: FONT_FAMILY.bold, fontSize: 9, color: colors.textMuted, letterSpacing: 0.5 },
    sectionContainer: { marginBottom: SPACE.xl },
    sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: SPACE.md, paddingLeft: 4 },
    sectionTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 11, color: colors.textMuted, letterSpacing: 1.5 },
    countBadge: { backgroundColor: isDark ? '#1C1C1E' : '#E5E7EB', paddingHorizontal: 6, paddingVertical: 2, borderRadius: RADIUS.full, marginLeft: 'auto' },
    countBadgeText: { fontFamily: FONT_FAMILY.bold, fontSize: 10, color: colors.textMuted },
    exercisesList: { gap: 8 },
    exerciseCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      padding: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    exerciseName: { fontFamily: FONT_FAMILY.bold, fontSize: 14, color: colors.textPrimary, marginBottom: 4 },
    exerciseMetaBadge: { fontFamily: FONT_FAMILY.body, fontSize: 12, color: colors.textMuted },
    exerciseMetaWeight: { fontFamily: FONT_FAMILY.bold, fontSize: 12, color: colors.textPrimary },
    expandBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingVertical: 14,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    expandBtnText: { fontFamily: FONT_FAMILY.bold, fontSize: 12, color: colors.textMuted },
    progressionCard: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: 16,
      padding: SPACE.lg,
      marginBottom: SPACE.xl,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    pillRow: { flexDirection: 'row', gap: 8 },
    liftPill: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: RADIUS.full, backgroundColor: isDark ? 'rgba(255, 255, 255, 0.04)' : 'rgba(0, 0, 0, 0.05)' },
    liftPillActive: { backgroundColor: isDark ? 'rgba(255, 255, 255, 0.15)' : 'rgba(108, 92, 231, 0.15)' },
    liftPillText: { fontFamily: FONT_FAMILY.medium, fontSize: 12, color: colors.textMuted },
    liftPillTextActive: { color: isDark ? '#ffffff' : colors.accentPrimary, fontFamily: FONT_FAMILY.bold },
    segmentedControl: {
      flexDirection: 'row',
      backgroundColor: isDark ? 'rgba(0, 0, 0, 0.2)' : 'rgba(0, 0, 0, 0.04)',
      borderRadius: RADIUS.md,
      padding: 3,
      marginBottom: 16,
    },
    segmentBtn: { flex: 1, paddingVertical: 7, alignItems: 'center', justifyContent: 'center', borderRadius: RADIUS.md - 2 },
    segmentBtnActive: { backgroundColor: isDark ? 'rgba(255, 255, 255, 0.12)' : '#FFFFFF' },
    segmentText: { fontFamily: FONT_FAMILY.medium, fontSize: 12, color: colors.textMuted },
    segmentTextActive: { fontFamily: FONT_FAMILY.bold, color: colors.textPrimary },
    chartWrapper: { alignItems: 'center', justifyContent: 'center', marginTop: 4, overflow: 'hidden' },
    chartStyle: { marginVertical: 4, borderRadius: 12 },
    emptyChartBox: {
      height: 140,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(0, 0, 0, 0.15)' : 'rgba(0, 0, 0, 0.03)',
      borderRadius: RADIUS.md,
      paddingHorizontal: SPACE.xl,
    },
    emptyIconBadge: {
      width: 38,
      height: 38,
      borderRadius: RADIUS.full,
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    emptyChartTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 13, color: colors.textPrimary, marginBottom: 4 },
    emptyChartText: { fontFamily: FONT_FAMILY.body, fontSize: 12, color: colors.textMuted, textAlign: 'center', lineHeight: 18 },
    notesContainer: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: 16,
      padding: SPACE.lg,
      marginBottom: SPACE.xl,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    notesText: { fontFamily: FONT_FAMILY.body, fontSize: 14, color: colors.textPrimary, lineHeight: 20 },
    footer: { paddingHorizontal: 7, paddingTop: SPACE.sm },
    doneBtn: {
      backgroundColor: isDark ? '#ffffff' : colors.accentPrimary,
      paddingVertical: 14,
      width: '100%',
      borderRadius: RADIUS.lg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    doneBtnText: { fontFamily: FONT_FAMILY.bold, fontSize: 15, color: isDark ? '#000000' : '#ffffff', letterSpacing: 0.3 },
  });
