import { StyleSheet, Platform } from 'react-native';
import { FONT_FAMILY, SPACE, RADIUS } from '../../theme/tokens';

export const makeAddExerciseStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    modalBg: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: RADIUS.xxl,
      borderTopRightRadius: RADIUS.xxl,
      padding: SPACE.xl,
      paddingBottom: Platform.OS === 'ios' ? 40 : SPACE.xl,
      maxHeight: '90%',
      borderWidth: 1,
      borderColor: colors.border,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: SPACE.lg,
    },
    title: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 18,
      color: colors.textPrimary,
      letterSpacing: -0.3,
    },
    closeBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    scrollArea: {
      maxHeight: 520,
    },
    inputGroup: {
      marginBottom: SPACE.lg,
    },
    inputLabel: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 11,
      color: colors.textTertiary,
      letterSpacing: 1,
      marginBottom: SPACE.xs,
    },
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? '#1C1C1E' : colors.surface2 || colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: RADIUS.md,
      paddingHorizontal: SPACE.md,
      height: 48,
    },
    searchInput: {
      flex: 1,
      fontFamily: FONT_FAMILY.medium,
      fontSize: 15,
      color: colors.textPrimary,
    },
    dropdown: {
      position: 'absolute',
      top: 52,
      left: 0,
      right: 0,
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.1)' : colors.border,
      zIndex: 9999,
      elevation: 8,
      overflow: 'hidden',
    },
    suggestionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACE.md,
      paddingVertical: 10,
    },
    suggestionBorder: {
      borderTopWidth: 1,
      borderTopColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    suggestionName: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 14,
      color: colors.textPrimary,
    },
    suggestionMeta: {
      fontFamily: FONT_FAMILY.medium,
      fontSize: 11,
      marginTop: 2,
    },
    suggestionRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    suggestionSets: {
      fontFamily: FONT_FAMILY.mono,
      fontSize: 12,
      color: colors.textMuted,
    },
    aiLoadingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: SPACE.md,
    },
    aiLoadingText: {
      fontFamily: FONT_FAMILY.medium,
      fontSize: 13,
      color: colors.accentPrimary,
    },
    aiSuggestionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: SPACE.md,
      backgroundColor: isDark ? 'rgba(165,153,255,0.08)' : 'rgba(108,92,231,0.06)',
    },
    aiSuggestionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    aiSuggestionName: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 14,
      color: colors.textPrimary,
    },
    aiBadge: {
      backgroundColor: colors.accentPrimary,
      paddingHorizontal: 5,
      paddingVertical: 1,
      borderRadius: 4,
    },
    aiBadgeText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 9,
      color: '#fff',
    },
    lastSessionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
      backgroundColor: isDark ? 'rgba(165,153,255,0.1)' : 'rgba(108,92,231,0.08)',
      borderRadius: RADIUS.sm,
      alignSelf: 'flex-start',
    },
    lastSessionText: {
      fontFamily: FONT_FAMILY.medium,
      fontSize: 11,
      color: colors.accentPrimary,
    },
    metaRow: {
      flexDirection: 'row',
      gap: SPACE.sm,
      marginBottom: SPACE.lg,
    },
    inputCompact: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface2 || colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: RADIUS.md,
      paddingHorizontal: SPACE.sm,
      height: 44,
      fontFamily: FONT_FAMILY.bold,
      fontSize: 14,
      color: colors.textPrimary,
    },
    musclePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: RADIUS.full,
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.08)' : colors.border,
    },
    muscleDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    muscleText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 12,
      color: colors.textMuted,
    },
    input: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface2 || colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: RADIUS.md,
      paddingHorizontal: SPACE.md,
      height: 48,
      fontFamily: FONT_FAMILY.medium,
      fontSize: 14,
      color: colors.textPrimary,
    },
    masterSplitContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: SPACE.md,
      marginBottom: SPACE.md,
    },
    masterSplitTitle: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 14,
      color: colors.textPrimary,
    },
    masterSplitDesc: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
    },
    submitBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#ffffff' : colors.accentPrimary,
      paddingVertical: 14,
      borderRadius: RADIUS.lg,
      marginTop: SPACE.sm,
      marginBottom: SPACE.md,
    },
    submitBtnDisabled: {
      opacity: 0.4,
    },
    submitBtnText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 15,
      color: isDark ? '#000000' : '#ffffff',
    },
  });
