import { StyleSheet } from 'react-native';
import { FONT_FAMILY } from '../../theme/tokens';

export const makeAnimatedRestTimerStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    wrapper: {
      zIndex: 9999,
      alignSelf: 'center',
    },
    collapsedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? '#161619' : '#FFFFFF',
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: isDark ? 'rgba(165,153,255,0.42)' : 'rgba(108,92,231,0.3)',
      paddingHorizontal: 12,
      paddingVertical: 7,
      shadowColor: colors.accentPrimary || '#a599ff',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.35 : 0.15,
      shadowRadius: 10,
      elevation: 10,
      gap: 3,
    },
    collapsedTimeText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 14,
      color: colors.accentPrimary,
      letterSpacing: 0.5,
    },
    quickAddPill: {
      marginLeft: 6,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 10,
      backgroundColor: isDark ? 'rgba(165,153,255,0.14)' : 'rgba(108,92,231,0.1)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.25)' : 'rgba(108,92,231,0.2)',
    },
    quickAddText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 10.5,
      color: colors.accentPrimary,
    },
    expandedCapsule: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 10,
      paddingVertical: 7,
      gap: 6,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: isDark ? 0.5 : 0.15,
      shadowRadius: 12,
      elevation: 12,
    },
    dragGrip: {
      paddingRight: 2,
      justifyContent: 'center',
      alignItems: 'center',
    },
    actionBtn: {
      padding: 2,
      justifyContent: 'center',
      alignItems: 'center',
    },
    timeContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(165,153,255,0.1)' : 'rgba(108,92,231,0.08)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.2)' : 'rgba(108,92,231,0.15)',
    },
    timeText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 14,
      color: colors.accentPrimary,
      letterSpacing: 0.5,
    },
    divider: {
      width: 1,
      height: 16,
      backgroundColor: colors.border,
      marginHorizontal: 2,
    },
    skipBtn: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 10,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
    },
    skipText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 11,
      color: colors.textMuted,
    },
  });
