import { StyleSheet, Platform } from 'react-native';
import { FONT_FAMILY, FONT_SIZE, SPACE, RADIUS } from '../../theme/tokens';

export const makeStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'flex-end',
    },
    sheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingTop: 12,
      paddingHorizontal: 20,
      maxHeight: '92%',
      borderWidth: 1,
      borderColor: colors.border,
      borderBottomWidth: 0,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -8 },
      shadowOpacity: isDark ? 0.5 : 0.15,
      shadowRadius: 24,
      elevation: 16,
    },
    handle: {
      width: 38,
      height: 4,
      borderRadius: 2,
      backgroundColor: isDark ? 'rgba(255,255,255,0.2)' : 'rgba(0,0,0,0.15)',
      alignSelf: 'center',
      marginBottom: 16,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    headerLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginRight: 12,
    },
    iconBadge: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: isDark ? 'rgba(165,153,255,0.12)' : 'rgba(108,92,231,0.10)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.25)' : 'rgba(108,92,231,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 20,
      color: colors.textPrimary,
      letterSpacing: -0.3,
    },
    subtitle: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 12,
      color: colors.textTertiary,
      marginTop: 2,
    },
    closeBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    sectionLabel: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 11,
      color: colors.accentPrimary,
      letterSpacing: 1.5,
      marginBottom: 10,
    },
    label: {
      fontFamily: FONT_FAMILY.medium,
      fontSize: 12,
      color: colors.textTertiary,
      marginBottom: 6,
    },
    input: {
      backgroundColor: isDark ? '#161422' : '#F5F4FA',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.2)' : colors.border,
      borderRadius: 16,
      paddingHorizontal: 14,
      height: 48,
      fontFamily: FONT_FAMILY.medium,
      fontSize: 15,
      color: colors.textPrimary,
    },
    textArea: {
      height: 'auto' as any,
      paddingVertical: 12,
      textAlignVertical: 'top',
      marginBottom: 0,
    },
    goalPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: isDark ? '#14121d' : '#F5F4FA',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.08)' : colors.border,
      gap: 6,
    },
    goalPillActive: {
      borderColor: colors.accentPrimary,
      backgroundColor: isDark ? '#251e3d' : 'rgba(108,92,231,0.12)',
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.35 : 0.15,
      shadowRadius: 8,
      elevation: 0,
    },
    goalPillText: {
      fontFamily: FONT_FAMILY.medium,
      fontSize: 13,
      backgroundColor: 'transparent',
      includeFontPadding: false,
    },
    dayPill: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#14121d' : '#F5F4FA',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.08)' : colors.border,
    },
    dayPillActive: {
      borderColor: colors.accentPrimary,
      backgroundColor: isDark ? '#251e3d' : 'rgba(108,92,231,0.12)',
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0.3 : 0.15,
      shadowRadius: 8,
      elevation: 0,
    },
    dayPillText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 16,
      backgroundColor: 'transparent',
      includeFontPadding: false,
    },
    saveBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: isDark ? '#a599ff' : colors.accentPrimary,
      borderRadius: 26,
      height: 52,
      marginBottom: Platform.OS === 'ios' ? 32 : 16,
      marginTop: 12,
      shadowColor: colors.accentPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.45 : 0.25,
      shadowRadius: 14,
      elevation: 8,
    },
    saveBtnText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 15,
      color: isDark ? '#080510' : '#FFFFFF',
      backgroundColor: 'transparent',
      includeFontPadding: false,
    },
  });

// Thin alias for the existing style object in modal context
export const s = StyleSheet.create({
  pill: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
  },
  pillText: {
    fontFamily: FONT_FAMILY.body,
    fontSize: 13,
    backgroundColor: 'transparent',
    includeFontPadding: false,
  },
});

