import { StyleSheet } from 'react-native';
import { FONT_FAMILY, FONT_SIZE, SPACE, RADIUS } from '../../theme/tokens';

export const makeGymScheduleStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.82)',
      justifyContent: 'flex-end',
    },
    card: {
      backgroundColor: isDark ? '#000000' : colors.surface,
      borderTopLeftRadius: RADIUS.xxl,
      borderTopRightRadius: RADIUS.xxl,
      height: '88%',
      maxHeight: '92%',
      borderTopWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.10)' : colors.border,
      overflow: 'hidden',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACE.lg,
      paddingVertical: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: isDark ? 'rgba(255,255,255,0.08)' : colors.border,
    },
    title: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 18,
      color: colors.textPrimary,
    },
    closeBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    contentContainer: {
      paddingHorizontal: SPACE.lg,
      paddingTop: 16,
      paddingBottom: 36,
    },
    description: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 12.5,
      color: colors.textSecondary,
      lineHeight: 18,
      marginBottom: 16,
    },
    dayRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? '#09090C' : '#F9F8FD',
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.07)' : colors.border,
    },
    dayRowRest: {
      backgroundColor: isDark ? '#070604' : '#FFFBF5',
      borderColor: isDark ? 'rgba(255,159,77,0.22)' : 'rgba(234,88,12,0.18)',
    },
    dayIconBox: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    dayInfo: {
      flex: 1,
      marginRight: 10,
    },
    dayName: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 14.5,
      color: colors.textPrimary,
    },
    dayNameRest: {
      color: isDark ? '#FF9F4D' : '#EA580C',
    },
    planFocus: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 11.5,
      color: colors.textSecondary,
      marginTop: 2,
    },
    planFocusRest: {
      color: isDark ? 'rgba(255,159,77,0.75)' : '#EA580C',
    },
    timeBlock: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    timeText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 12,
      color: colors.textPrimary,
      textAlign: 'right',
    },
    timeSubText: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 10,
      color: colors.textTertiary,
      textAlign: 'right',
      marginTop: 1,
    },
    notSetText: {
      fontFamily: FONT_FAMILY.medium,
      fontSize: 11.5,
      color: colors.textTertiary,
    },
    saveBtn: {
      backgroundColor: colors.accentPrimary,
      borderRadius: 14,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 12,
    },
    saveBtnText: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 14.5,
      color: '#000000',
    },
    editContainer: {
      paddingBottom: 24,
    },
    editHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
      paddingBottom: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: isDark ? 'rgba(255,255,255,0.08)' : colors.border,
    },
    settingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 13,
      paddingHorizontal: 14,
      backgroundColor: isDark ? '#09090C' : '#F9F8FD',
      borderRadius: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.07)' : colors.border,
    },
    settingLabel: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 13.5,
      color: colors.textPrimary,
    },
    settingSub: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
    },
  });
