import { StyleSheet } from 'react-native';
import { COLORS, RADIUS, FONT_FAMILY, FONT_SIZE, SPACE, SHADOW } from '../../theme/tokens';

export const makeStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    container: {
      paddingHorizontal: 8,
      paddingBottom: 24,
    },

    // Title Row
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 10,
      marginTop: 0,
    },
    title: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.textPrimary,
      fontFamily: FONT_FAMILY.bold,
    },
    subtitle: {
      fontSize: 12,
      color: colors.textTertiary,
      marginTop: 2,
      fontFamily: FONT_FAMILY.medium,
    },
    restBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: isDark ? 'rgba(165,153,255,0.1)' : 'rgba(108,92,231,0.08)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.25)' : 'rgba(108,92,231,0.2)',
      borderRadius: RADIUS.full,
      paddingHorizontal: 12,
      paddingVertical: 5,
    },
    restBadgeText: {
      fontSize: 11,
      color: colors.accentPrimary,
      fontFamily: FONT_FAMILY.bold,
    },

    // Empty Card
    emptyCard: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: RADIUS.xl,
      alignItems: 'center',
      paddingVertical: 40,
      paddingHorizontal: 24,
      gap: 10,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    emptyText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    emptySubtext: {
      fontSize: 12,
      color: colors.textTertiary,
      textAlign: 'center',
      lineHeight: 18,
    },

    // Section Headers
    sectionLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textTertiary,
      letterSpacing: 1.2,
      fontFamily: FONT_FAMILY.bold,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },

    // Shared Card Wrapper
    card: {
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: RADIUS.xl,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },

    // Global KPI Stats
    statsRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
    },
    statCard: {
      flex: 1,
      backgroundColor: isDark ? '#1C1C1E' : (colors.surface2 || '#F8F7FC'),
      borderRadius: RADIUS.xl,
      padding: 14,
      alignItems: 'center',
      gap: 2,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    statValue: {
      fontSize: 21,
      fontWeight: '700',
      color: colors.textPrimary,
      fontFamily: FONT_FAMILY.bold,
    },
    statSuffix: {
      fontSize: 12,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
    },
    statLabel: {
      fontSize: 10,
      color: colors.textTertiary,
      textAlign: 'center',
      fontFamily: FONT_FAMILY.medium,
    },
    changeBadge: {
      fontSize: 10,
      fontWeight: '600',
      marginTop: 2,
      fontFamily: FONT_FAMILY.medium,
    },
    changeBadgeNeutral: {
      fontSize: 10,
      color: colors.textTertiary,
      marginTop: 2,
      fontFamily: FONT_FAMILY.medium,
    },

    // Highlights & Top Lifts (Subtle Luxury Obsidian)
    highlightCard: {
      backgroundColor: isDark ? '#121215' : colors.surface,
      borderRadius: RADIUS.xl,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(230, 200, 117, 0.16)' : 'rgba(217, 119, 6, 0.2)',
    },
    highlightHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? 'rgba(255,255,255,0.04)' : colors.border,
    },
    trophyCircle: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: 'rgba(230, 200, 117, 0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(230, 200, 117, 0.22)',
    },
    highlightTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: '#e6c875',
      letterSpacing: 1.2,
      fontFamily: FONT_FAMILY.bold,
    },
    highlightSubtitle: {
      fontSize: 9,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
      marginTop: 1,
    },
    highlightBadge: {
      backgroundColor: 'rgba(230, 200, 117, 0.08)',
      borderWidth: 1,
      borderColor: 'rgba(230, 200, 117, 0.2)',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: RADIUS.full,
    },
    highlightBadgeText: {
      fontSize: 10,
      fontFamily: FONT_FAMILY.bold,
      color: '#e6c875',
    },
    highlightPodsGrid: {
      flexDirection: 'row',
      gap: 8,
    },
    highlightPod: {
      flex: 1,
      backgroundColor: isDark ? '#1C1C1E' : (colors.surface2 || '#F8F7FC'),
      borderRadius: RADIUS.lg,
      padding: 12,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
      gap: 4,
    },
    highlightPodHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginBottom: 2,
    },
    highlightPodTag: {
      fontSize: 9,
      fontWeight: '700',
      color: '#e6c875',
      letterSpacing: 0.9,
      fontFamily: FONT_FAMILY.bold,
    },
    highlightLiftName: {
      fontSize: 12.5,
      fontWeight: '600',
      color: colors.textPrimary,
      fontFamily: FONT_FAMILY.medium,
      lineHeight: 16,
    },
    highlightStatRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 4,
      marginTop: 2,
    },
    highlightWeightText: {
      fontSize: 16,
      fontWeight: '700',
      color: '#e6c875',
      fontFamily: FONT_FAMILY.bold,
    },
    highlightUnit: {
      fontSize: 10,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
    },
    highlightRepsText: {
      fontSize: 11,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
    },

    // Muscle Donut Grid
    adherenceBadge: {
      backgroundColor: isDark ? 'rgba(94, 218, 158, 0.12)' : 'rgba(16, 185, 129, 0.12)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(94, 218, 158, 0.25)' : 'rgba(16, 185, 129, 0.25)',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: RADIUS.full,
    },
    adherenceBadgeText: {
      fontSize: 10,
      fontFamily: FONT_FAMILY.bold,
      color: isDark ? '#5EDA9E' : '#059669',
    },
    muscleGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    muscleCard: {
      width: '30.5%',
      alignItems: 'center',
      gap: 3,
      paddingVertical: 6,
    },
    ringWrapper: {
      position: 'relative',
      width: 66,
      height: 66,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ringCenter: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
    },
    ringNum: {
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 16,
      color: colors.textPrimary,
      fontFamily: FONT_FAMILY.bold,
    },
    ringTarget: {
      fontSize: 9,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
    },
    ringUnit: {
      fontSize: 8,
      color: colors.textTertiary,
      lineHeight: 10,
      fontFamily: FONT_FAMILY.bold,
    },
    muscleName: {
      fontSize: 11,
      color: colors.textPrimary,
      textAlign: 'center',
      fontFamily: FONT_FAMILY.medium,
      marginTop: 2,
    },
    muscleChangeRow: {
      height: 14,
      justifyContent: 'center',
    },

    // Daily Volume Bar Chart
    barChart: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      height: 76,
      gap: 6,
      marginTop: 10,
    },
    barCol: {
      flex: 1,
      alignItems: 'center',
      gap: 6,
      height: '100%',
      justifyContent: 'flex-end',
    },
    barTrack: {
      flex: 1,
      width: '100%',
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : '#EAE9F2',
      borderRadius: RADIUS.sm,
      overflow: 'hidden',
      justifyContent: 'flex-end',
    },
    barFill: {
      width: '100%',
      borderRadius: RADIUS.sm,
      minHeight: 4,
    },
    barLabel: {
      fontSize: 10,
      color: colors.textTertiary,
    },

    // Cardio Summary (Luxury Obsidian Pods)
    cardioCard: {
      backgroundColor: isDark ? '#121215' : colors.surface,
      borderRadius: RADIUS.xl,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 159, 77, 0.18)' : 'rgba(217, 119, 6, 0.2)',
    },
    cardioHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? 'rgba(255,255,255,0.04)' : colors.border,
    },
    cardioIconBadge: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: 'rgba(255, 159, 77, 0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255, 159, 77, 0.25)',
    },
    cardioSectionTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: isDark ? colors.accentAmber : '#D97706',
      letterSpacing: 1.2,
      fontFamily: FONT_FAMILY.bold,
    },
    cardioSectionSubtitle: {
      fontSize: 9,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
      marginTop: 1,
    },
    cardioTagPill: {
      backgroundColor: isDark ? 'rgba(255, 159, 77, 0.1)' : 'rgba(217, 119, 6, 0.1)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 159, 77, 0.22)' : 'rgba(217, 119, 6, 0.22)',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: RADIUS.full,
    },
    cardioTagText: {
      fontSize: 10,
      fontFamily: FONT_FAMILY.bold,
      color: isDark ? colors.accentAmber : '#D97706',
    },
    cardioPodsGrid: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 10,
    },
    cardioPod: {
      flex: 1,
      backgroundColor: isDark ? '#1C1C1E' : (colors.surface2 || '#F8F7FC'),
      borderRadius: RADIUS.lg,
      padding: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
      gap: 2,
    },
    cardioPodIconBox: {
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 2,
    },
    cardioPodValue: {
      fontSize: 16,
      fontFamily: FONT_FAMILY.bold,
      color: colors.textPrimary,
      fontWeight: '700',
    },
    cardioPodUnit: {
      fontSize: 10,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
    },
    cardioPodLabel: {
      fontSize: 9.5,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
      marginTop: 1,
    },
    cardioFooterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? 'rgba(255, 159, 77, 0.05)' : 'rgba(249, 115, 22, 0.08)',
      borderRadius: RADIUS.md,
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 159, 77, 0.12)' : 'rgba(249, 115, 22, 0.15)',
    },
    cardioFooterItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    cardioFooterText: {
      fontSize: 10.5,
      color: colors.textSecondary,
      fontFamily: FONT_FAMILY.medium,
    },

    // Warning Card
    warningCard: {
      backgroundColor: isDark ? 'rgba(255,159,77,0.06)' : 'rgba(249, 115, 22, 0.08)',
      borderRadius: RADIUS.xl,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,159,77,0.2)' : 'rgba(249, 115, 22, 0.25)',
      gap: 6,
    },
    warningHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    warningTitle: {
      fontSize: 10,
      fontWeight: '700',
      color: isDark ? colors.accentAmber : '#EA580C',
      letterSpacing: 1.2,
      fontFamily: FONT_FAMILY.bold,
    },
    warningBody: {
      fontSize: 11,
      color: colors.textMuted,
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 2,
    },
    chip: {
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
      borderRadius: RADIUS.full,
      paddingHorizontal: 9,
      paddingVertical: 3,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,159,77,0.2)' : 'rgba(249, 115, 22, 0.25)',
    },
    chipText: {
      fontSize: 10,
      color: isDark ? colors.accentAmber : '#EA580C',
      fontFamily: FONT_FAMILY.bold,
    },

    // ── GYM-GPT AI Section Styles (Minimalist Obsidian Editorial) ──────────────
    aiCard: {
      backgroundColor: isDark ? '#121215' : colors.surface,
      borderRadius: RADIUS.xl,
      padding: 18,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.18)' : 'rgba(108,92,231,0.15)',
    },
    aiCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    aiSparkleBadge: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: isDark ? 'rgba(165,153,255,0.12)' : 'rgba(108,92,231,0.10)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.25)' : 'rgba(108,92,231,0.2)',
    },
    aiSectionTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.accentPrimary,
      letterSpacing: 1.2,
      fontFamily: FONT_FAMILY.bold,
    },
    aiSectionSubtitle: {
      fontSize: 9,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
      marginTop: 1,
    },
    aiScoreBadge: {
      backgroundColor: isDark ? 'rgba(94, 218, 158, 0.12)' : 'rgba(16, 185, 129, 0.12)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(94, 218, 158, 0.25)' : 'rgba(16, 185, 129, 0.25)',
      paddingHorizontal: 9,
      paddingVertical: 3,
      borderRadius: RADIUS.full,
    },
    aiScoreBadgeText: {
      fontSize: 10,
      fontFamily: FONT_FAMILY.bold,
      color: isDark ? '#5EDA9E' : '#059669',
    },
    aiRefreshBtn: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    aiLoadingState: {
      paddingVertical: 24,
      alignItems: 'center',
      gap: 10,
    },
    aiLoadingText: {
      fontSize: 12,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
      textAlign: 'center',
    },
    aiContent: {
      gap: 14,
    },
    aiHeroBlock: {
      gap: 6,
      paddingBottom: 4,
    },
    aiHeadline: {
      fontSize: 16,
      color: colors.textPrimary,
      fontFamily: FONT_FAMILY.bold,
      lineHeight: 22,
      letterSpacing: -0.2,
    },
    aiVerdict: {
      fontSize: 12.5,
      color: colors.textSecondary,
      fontFamily: FONT_FAMILY.body,
      lineHeight: 19,
    },
    aiBlock: {
      backgroundColor: isDark ? '#1C1C1E' : (colors.surface2 || '#F8F7FC'),
      borderRadius: RADIUS.lg,
      padding: 14,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
      gap: 6,
    },
    aiBlockHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 4,
    },
    aiBlockTitle: {
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 1.1,
      fontFamily: FONT_FAMILY.bold,
    },
    aiVolumePill: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: isDark ? 'rgba(94, 218, 158, 0.09)' : 'rgba(16, 185, 129, 0.10)',
      borderRadius: RADIUS.sm,
      paddingHorizontal: 8,
      paddingVertical: 3,
      marginBottom: 6,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(94, 218, 158, 0.2)' : 'rgba(16, 185, 129, 0.25)',
    },
    aiVolumePillText: {
      fontSize: 11,
      fontFamily: FONT_FAMILY.bold,
      color: isDark ? '#5EDA9E' : '#059669',
    },
    aiBulletRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 6,
      paddingLeft: 2,
      marginBottom: 2,
    },
    aiBulletDot: {
      fontSize: 12,
      color: colors.textTertiary,
      lineHeight: 17,
    },
    aiBulletText: {
      flex: 1,
      fontSize: 12,
      color: colors.textSecondary,
      fontFamily: FONT_FAMILY.body,
      lineHeight: 18,
    },
    aiSubSummary: {
      fontSize: 11,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.body,
      marginTop: 4,
      fontStyle: 'italic',
      lineHeight: 16,
    },
    aiTrajectoryText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontFamily: FONT_FAMILY.body,
      lineHeight: 18,
      marginBottom: 4,
    },
    aiFatigueBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: isDark ? 'rgba(255, 159, 77, 0.08)' : 'rgba(249, 115, 22, 0.10)',
      borderRadius: RADIUS.md,
      paddingHorizontal: 10,
      paddingVertical: 6,
      marginTop: 6,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 159, 77, 0.2)' : 'rgba(249, 115, 22, 0.25)',
    },
    aiFatigueText: {
      flex: 1,
      fontSize: 11.5,
      color: isDark ? colors.accentAmber : '#EA580C',
      fontFamily: FONT_FAMILY.medium,
      lineHeight: 16,
    },
    aiDirectiveCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: isDark ? '#1C1C1E' : (colors.surface2 || '#F8F7FC'),
      borderRadius: RADIUS.md,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.12)' : 'rgba(108,92,231,0.15)',
    },
    aiDirectiveNumPill: {
      width: 22,
      height: 22,
      borderRadius: 6,
      backgroundColor: isDark ? 'rgba(165,153,255,0.15)' : 'rgba(108,92,231,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
    },
    aiDirectiveNumText: {
      fontSize: 10,
      fontFamily: FONT_FAMILY.bold,
      color: colors.accentPrimary,
    },
    aiDirectiveText: {
      flex: 1,
      fontSize: 12,
      color: colors.textPrimary,
      fontFamily: FONT_FAMILY.body,
      lineHeight: 18,
    },
    aiPromptState: {
      paddingVertical: 12,
      paddingHorizontal: 4,
      gap: 8,
    },
    aiPromptTitle: {
      fontSize: 13,
      fontFamily: FONT_FAMILY.bold,
      color: colors.textPrimary,
    },
    aiPromptSub: {
      fontSize: 12,
      color: colors.textSecondary,
      fontFamily: FONT_FAMILY.body,
      lineHeight: 17,
    },
    aiGenerateBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: isDark ? 'rgba(165,153,255,0.12)' : 'rgba(108,92,231,0.10)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.3)' : 'rgba(108,92,231,0.25)',
      borderRadius: RADIUS.lg,
      paddingVertical: 12,
      marginTop: 4,
    },
    aiGenerateBtnText: {
      fontSize: 13,
      fontFamily: FONT_FAMILY.bold,
      color: colors.accentPrimary,
    },
    aiErrorState: {
      alignItems: 'center',
      gap: 8,
      paddingVertical: 20,
      paddingHorizontal: 12,
    },
    aiErrorText: {
      fontSize: 12,
      color: colors.textTertiary,
      fontFamily: FONT_FAMILY.medium,
      textAlign: 'center',
    },
    aiErrorRetryBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: isDark ? 'rgba(165,153,255,0.12)' : 'rgba(108,92,231,0.10)',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(165,153,255,0.25)' : 'rgba(108,92,231,0.2)',
      borderRadius: RADIUS.lg,
      paddingHorizontal: 14,
      paddingVertical: 8,
      marginTop: 4,
    },
    aiErrorRetryText: {
      fontSize: 12,
      fontFamily: FONT_FAMILY.bold,
      color: colors.accentPrimary,
    },
    aiFoldBtn: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)',
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 2,
    },
    aiCardCollapsed: {
      paddingBottom: 12,
    },
    aiCardHeaderCollapsed: {
      marginBottom: 8,
      paddingBottom: 10,
    },
    aiCollapsedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 4,
      paddingHorizontal: 2,
    },
    aiCollapsedLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flex: 1,
      paddingRight: 8,
    },
    aiClickToOpenText: {
      fontSize: 12,
      fontFamily: FONT_FAMILY.bold,
      color: colors.accentPrimary,
      letterSpacing: 0.2,
    },
    aiCollapsedDot: {
      fontSize: 11,
      color: colors.textTertiary,
    },
    aiCollapsedHeadlineText: {
      fontSize: 11,
      color: colors.textSecondary,
      fontFamily: FONT_FAMILY.medium,
      flex: 1,
    },
  });

