import { StyleSheet, Platform } from 'react-native';
import { FONT_FAMILY, SPACE, RADIUS, SHADOW } from '../../theme/tokens';

export const makeZenGymAiStyles = (colors: any, isDark: boolean = true) =>
  StyleSheet.create({
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'transparent',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.72)',
    },
    container: {
      flex: 1,
      marginTop: '15%',
      backgroundColor: isDark ? '#000000' : colors.background,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.08)' : colors.border,
      borderBottomWidth: 0,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -6 },
      shadowOpacity: isDark ? 0.8 : 0.15,
      shadowRadius: 24,
      elevation: 24,
    },
    handleWrap: {
      alignItems: 'center',
      paddingTop: 8,
      paddingBottom: 4,
      backgroundColor: isDark ? '#000000' : colors.background,
    },
    handle: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.22)' : 'rgba(0, 0, 0, 0.15)',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACE.lg,
      paddingVertical: SPACE.md,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? 'rgba(255,255,255,0.06)' : colors.border,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    avatarBox: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(165,153,255,0.15)' : 'rgba(108,92,231,0.12)',
    },
    title: {
      fontFamily: FONT_FAMILY.bold,
      fontSize: 16,
      color: colors.textPrimary,
    },
    subtitle: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 11,
      color: colors.accentPrimary,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    iconBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)',
    },
    chatArea: {
      flex: 1,
      paddingHorizontal: SPACE.lg,
      paddingTop: SPACE.md,
    },
    quickChipsScroll: {
      paddingVertical: 8,
      gap: 8,
    },
    quickChip: {
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: RADIUS.full,
      backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : colors.surface,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.08)' : colors.border,
    },
    quickChipText: {
      fontFamily: FONT_FAMILY.medium,
      fontSize: 12,
      color: colors.textPrimary,
    },
    msgRow: {
      marginVertical: 6,
      flexDirection: 'row',
      gap: 8,
    },
    msgRowUser: {
      justifyContent: 'flex-end',
    },
    msgRowAi: {
      justifyContent: 'flex-start',
    },
    msgBubbleUser: {
      maxWidth: '82%',
      backgroundColor: isDark ? '#2C2C2E' : colors.surface2 || colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 18,
      borderBottomRightRadius: 4,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.06)' : colors.border,
    },
    msgTextUser: {
      fontFamily: FONT_FAMILY.body,
      fontSize: 14,
      color: colors.textPrimary,
      lineHeight: 20,
    },
    msgBubbleAi: {
      maxWidth: '90%',
      backgroundColor: isDark ? 'rgba(255,255,255,0.03)' : colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 18,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.05)' : colors.border,
    },
    inputBarWrapper: {
      paddingHorizontal: SPACE.md,
      paddingTop: 8,
      paddingBottom: Platform.OS === 'ios' ? 24 : 12,
      backgroundColor: isDark ? '#000000' : colors.background,
      borderTopWidth: 1,
      borderTopColor: isDark ? 'rgba(255,255,255,0.06)' : colors.border,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? '#1C1C1E' : colors.surface,
      borderRadius: 24,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255,255,255,0.08)' : colors.border,
      gap: 8,
    },
    textInput: {
      flex: 1,
      fontFamily: FONT_FAMILY.body,
      fontSize: 14,
      color: colors.textPrimary,
      maxHeight: 100,
      paddingVertical: Platform.OS === 'ios' ? 8 : 4,
    },
    sendBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? '#ffffff' : colors.accentPrimary,
    },
  });
