/**
 * attendanceStyles.ts
 * All styles for the Attendance module — extracted from the main screen.
 */
import { StyleSheet } from 'react-native';
import { FONT_FAMILY, FONT_SIZE, SPACE, RADIUS } from '../../theme/tokens';

export const makeStyles = (colors: any, isDark: boolean = true) => StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },

  overviewCard: {
    marginHorizontal: 0,
    marginTop: 12,
    marginBottom: 12,
    padding: SPACE.lg,
    backgroundColor: isDark ? colors.surface : '#FFFFFF',
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#E2E1EA',
    borderRadius: RADIUS.xl,
  },
  overviewTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 13, color: isDark ? colors.textPrimary : colors.textMuted },
  overviewStats: { fontFamily: FONT_FAMILY.body, fontSize: 12, color: colors.textTertiary },
  overviewPct: { fontFamily: FONT_FAMILY.title, fontSize: 32, fontWeight: 'bold' as const },
  progressBarBg: { flex: 1, height: 8, backgroundColor: isDark ? 'rgba(255,255,255,0.1)' : '#E2E1EA', borderRadius: 4, overflow: 'hidden' as const },
  progressBarFill: { height: '100%' as const, borderRadius: 4 },

  warningBanner: {
    marginHorizontal: 0,
    marginBottom: SPACE.sm,
    padding: SPACE.md,
    backgroundColor: isDark ? 'rgba(239,68,68,0.10)' : 'rgba(239,68,68,0.08)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(239,68,68,0.30)' : '#FEE2E2',
    borderRadius: RADIUS.lg,
  },
  warningTitle: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 12,
    color: isDark ? '#fca5a5' : '#DC2626',
  },
  warningText: {
    fontSize: 11,
    color: isDark ? '#fca5a5' : '#991B1B',
  },
  warningIcon: {
    color: isDark ? '#f59e0b' : '#D97706',
  },

  weekStrip: { flexDirection: 'row' as const, paddingHorizontal: 16, gap: 6, marginBottom: SPACE.md },
  weekPill: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 12,
    alignItems: 'center' as const,
    backgroundColor: isDark ? colors.surface : '#FFFFFF',
    borderWidth: 1,
    borderColor: colors.border,
  },
  weekPillActive: {
    backgroundColor: colors.accentPrimary,
    borderColor: colors.accentPrimary,
  },
  weekPillToday: {
    backgroundColor: isDark ? 'rgba(165,153,255,0.16)' : 'rgba(108,92,231,0.12)',
    borderColor: isDark ? 'rgba(165,153,255,0.45)' : 'rgba(108,92,231,0.35)',
  },
  weekPillDay: { fontSize: 10, color: colors.textMuted, marginBottom: 2, fontWeight: 'bold' as const },
  weekPillLabel: { fontSize: 12, color: colors.textPrimary, fontWeight: 'bold' as const },

  scheduleHeader: { paddingHorizontal: 16, marginBottom: SPACE.sm },
  scheduleTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 16, color: colors.textPrimary },

  list: { paddingHorizontal: 0, paddingBottom: 100 },
  emptyState: {
    alignItems: 'center' as const,
    paddingVertical: 60,
    gap: 12,
    backgroundColor: isDark ? colors.surface : '#FFFFFF',
    borderWidth: 1,
    borderColor: isDark ? colors.border : '#E2E1EA',
    borderRadius: RADIUS.xl,
  },
  emptyText: { fontFamily: FONT_FAMILY.bold, fontSize: 16, color: colors.textMuted },

  subjectCard: {
    backgroundColor: isDark ? colors.surface : '#FFFFFF',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: RADIUS.lg,
    marginBottom: SPACE.sm,
    overflow: 'hidden' as const,
  },
  subjectHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    padding: SPACE.md,
    backgroundColor: isDark ? 'rgba(0,0,0,0.1)' : '#F8F7FC',
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  subjectName: { fontFamily: FONT_FAMILY.bold, fontSize: 15, color: colors.textPrimary },
  subjectTarget: { fontFamily: FONT_FAMILY.body, fontSize: 11, color: colors.textMuted },

  sessionSection: { flexDirection: 'row' as const, padding: SPACE.md },
  sessionInfo: { flex: 1, paddingRight: SPACE.md },
  sessionLabel: { fontSize: 10, color: colors.textMuted, fontWeight: 'bold' as const, marginBottom: 4 },
  sessionPct: { fontFamily: FONT_FAMILY.title, fontSize: 24, fontWeight: 'bold' as const },
  sessionCounts: { fontSize: 11, color: colors.textSecondary },
  sessionUrgency: { fontSize: 10, marginTop: 4, fontWeight: 'bold' as const },
  sessionList: { flex: 2, gap: 6 },
  logRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    backgroundColor: isDark ? colors.background : '#F5F4FA',
    borderWidth: 1,
    borderColor: colors.border,
    padding: 8,
    borderRadius: 8,
  },
  logLabel: { fontSize: 12, fontWeight: 'bold' as const, color: colors.textPrimary },
  logStatus: { fontSize: 11, fontWeight: 'bold' as const },
  undoBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: isDark ? '#2c2c2e' : '#EAE9F2',
    borderWidth: isDark ? 0 : 1,
    borderColor: isDark ? 'transparent' : '#E2E1EA',
  },
  actionBtn: {
    padding: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : '#F5F4FA',
  },
  inlineLogBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: isDark ? 'rgba(255,255,255,0.02)' : '#FFFFFF',
  },

  // Action Buttons for sessions
  btnPresent: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: isDark ? '#2c2c2e' : 'rgba(16,185,129,0.12)',
    borderWidth: isDark ? 0 : 1,
    borderColor: isDark ? 'transparent' : 'rgba(16,185,129,0.25)',
  },
  btnAbsent: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: isDark ? '#2c2c2e' : 'rgba(239,68,68,0.12)',
    borderWidth: isDark ? 0 : 1,
    borderColor: isDark ? 'transparent' : 'rgba(239,68,68,0.25)',
  },
  btnCancelled: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: isDark ? '#2c2c2e' : 'rgba(107,114,128,0.12)',
    borderWidth: isDark ? 0 : 1,
    borderColor: isDark ? 'transparent' : '#E2E1EA',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },

  // Modals
  modalRoot: { flex: 1, backgroundColor: colors.background },
  modalHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    padding: SPACE.md,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: { fontFamily: FONT_FAMILY.title, fontSize: 18, color: colors.textPrimary },
  modalHeaderBtn: { padding: 4 },

  configCard: {
    backgroundColor: isDark ? colors.surface : '#FFFFFF',
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    marginBottom: SPACE.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  configName: { fontFamily: FONT_FAMILY.bold, fontSize: 16, color: colors.accentPrimary },
  configInputName: { fontFamily: FONT_FAMILY.bold, fontSize: 16, color: colors.accentPrimary, padding: 0, flex: 1, borderBottomWidth: 1, borderColor: colors.border },
  configInputSmall: { width: 40, height: 24, backgroundColor: colors.background, borderRadius: 4, textAlign: 'center' as const, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border, padding: 0 },
  configInputGrid: { width: 28, height: 24, backgroundColor: colors.background, borderRadius: 4, textAlign: 'center' as const, color: colors.textPrimary, borderWidth: 1, borderColor: colors.border, padding: 0 },

  historyCard: {
    backgroundColor: isDark ? colors.surface : '#FFFFFF',
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    marginBottom: SPACE.sm,
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    borderWidth: 1,
    borderColor: colors.border,
  },

  overlayBg: {
    flex: 1,
    justifyContent: 'flex-end' as const,
    backgroundColor: isDark ? 'rgba(0,0,0,0.6)' : 'rgba(0,0,0,0.3)',
  },
  sheet: {
    backgroundColor: isDark ? colors.surface : '#FFFFFF',
    padding: SPACE.xl,
    borderTopLeftRadius: RADIUS.xl,
    borderTopRightRadius: RADIUS.xl,
    borderWidth: isDark ? 0 : 1,
    borderColor: colors.border,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: isDark ? 'rgba(255,255,255,0.12)' : '#D1D0DA',
    alignSelf: 'center' as const,
    marginBottom: 20,
  },
  sheetTitle: { fontFamily: FONT_FAMILY.bold, fontSize: 16, color: colors.textPrimary, textAlign: 'center' as const, marginBottom: SPACE.md },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: isDark ? colors.background : '#F5F4FA',
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 8,
  },
  chipActive: { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary },
  chipText: { fontSize: 12, color: colors.textPrimary },
  extraBtn: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: isDark ? 'rgba(255,255,255,0.05)' : '#F5F4FA', borderColor: colors.border },

  // Extra Class Modal
  subjectSelectRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 6,
    backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : '#F5F4FA',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255,255,255,0.06)' : '#E2E1EA',
  },
  subjectSelectRowActive: {
    backgroundColor: isDark ? 'rgba(165,153,255,0.08)' : 'rgba(108,92,231,0.10)',
    borderColor: isDark ? 'rgba(165,153,255,0.25)' : '#6C5CE7',
  },
  subjectSelectDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: isDark ? 'rgba(255,255,255,0.2)' : '#D1D0DA',
  },
  subjectSelectText: {
    flex: 1,
    fontFamily: FONT_FAMILY.medium,
    fontSize: 14,
    color: isDark ? '#8e8e93' : '#4B5563',
  },
  extraTypeRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: isDark ? 'rgba(255,255,255,0.06)' : '#E2E1EA',
  },
  extraTypeLabel: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 13,
    color: colors.textPrimary,
    letterSpacing: 0.3,
  },
  extraTypeActions: { flexDirection: 'row' as const, gap: 8 },
  extraActionBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 5,
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
  },
  extraActionAttended: {
    backgroundColor: isDark ? 'rgba(94,218,158,0.08)' : 'rgba(16,185,129,0.10)',
    borderColor: isDark ? 'rgba(94,218,158,0.2)' : 'rgba(16,185,129,0.25)',
  },
  extraActionAttendedText: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 13,
    color: isDark ? '#5eda9e' : '#059669',
  },
  extraActionMissed: {
    backgroundColor: isDark ? 'rgba(255,105,97,0.08)' : 'rgba(239,68,68,0.10)',
    borderColor: isDark ? 'rgba(255,105,97,0.2)' : 'rgba(239,68,68,0.25)',
  },
  extraActionMissedText: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 13,
    color: isDark ? '#ff6961' : '#DC2626',
  },
  extraCancelBtn: { marginTop: 16, alignItems: 'center' as const, paddingVertical: 12 },
  extraCancelText: { fontFamily: FONT_FAMILY.medium, fontSize: 14, color: colors.textMuted },

  // ── Single Morphing Sticky Header Styles ─────────────────────────────────
  topHeaderWrapper: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    backgroundColor: 'transparent',
  },
  headerInner: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 4,
    backgroundColor: 'transparent',
  },
  headerTitle: {
    fontSize: 21,
    fontWeight: '700' as const,
    fontFamily: FONT_FAMILY.bold,
    color: colors.textPrimary,
  },
  headerActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 2,
  },
  morphBtn: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    minWidth: 36,
  },
  morphBtnIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    position: 'relative' as const,
  },
  morphBtnPill: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    backgroundColor: isDark ? 'rgba(255,255,255,0.09)' : 'rgba(255,255,255,0.85)',
    borderWidth: 1,
    borderColor: isDark ? 'rgba(255,255,255,0.14)' : '#E2E1EA',
  },
  morphBtnPillAccent: {
    backgroundColor: isDark ? 'rgba(165,153,255,0.16)' : 'rgba(108,92,231,0.12)',
    borderColor: isDark ? 'rgba(165,153,255,0.32)' : 'rgba(108,92,231,0.30)',
  },
  morphBtnPillHoliday: {
    backgroundColor: isDark ? 'rgba(251,191,36,0.14)' : 'rgba(245,158,11,0.15)',
    borderColor: isDark ? 'rgba(251,191,36,0.35)' : '#D97706',
  },
  headerBtnText: {
    fontSize: 8.5,
    color: colors.textTertiary,
    fontFamily: FONT_FAMILY.medium,
    marginTop: 1,
    textAlign: 'center' as const,
  },
});
